---
system:
  debug: true
  key: no_key
  path:
    logs: 'Logs'
    cache: 'Cache'
    storage: 'Storage'
  retention:
    logs: 10
    cache: 3

site:
  title: ''
  root: index

auth:
  type: 'passkey'
  timeout: 3600
  session_key: 'MicroFrame_Session'
  passkey: pass@123

cache:
  default:
    type: local
    file: cache.db
    timeout: 10
  redis:
    type: redis
    host: 127.0.0.1
    port: 6279
    extra: ''
    timeout: 10
data:
  default:
    type: sqlite
    file: default.db
    timeout: 10
  sampledb:
    type: postgres
    host: 127.0.0.1
    port: 5432
    extra:
    user: root
    password: ''
    timeout: 10
